import type { Metadata } from 'next';
import Providers from '@/app/providers';
import { pretendard } from '@/styles/fonts';
import '@/styles/reset.css';
import MobileLayout from '@/components/layout/MobileLayout';

export const metadata: Metadata = {
  title: 'FINFRIENDS',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className={pretendard.className}>
      <Providers>
        <body>
          <MobileLayout>{children}</MobileLayout>
        </body>
      </Providers>
    </html>
  );
}
