import type { Metadata } from 'next';
import Providers from '@/app/providers';
import { pretendard } from '@/styles/fonts';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={pretendard.className}>
      <Providers>
        <body>{children}</body>
      </Providers>
    </html>
  );
}
